config/routes.rb
SocialTrainer::Application.routes.draw do
  root :to => 'welcome#index'

  resources :sessions, only: [:create, :new, :destroy]
  resources :users do
    resources :posts do
      resources :likes
      resources :comments do 
        resources :likes
      end
    end
  end

  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  post '/search' => 'search#index', as: "search"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	has_many :likes
	has_many :likers, through: :likes, source: :liker
	

	#VALIDATIONS
	validates_presence_of :post_id, :user_id, :content
end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: :friend_id
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User", foreign_key: :friend_id

	#VALIDATIONS
	validates_presence_of :user_id, :friend_id
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :liker, class_name: "User"
	belongs_to :post
	belongs_to :comment

	#VALIDATIONS
	validates_presence_of :liker_id, :value
	validates_uniqueness_of :liker_id, scope: :post_id

  def to_boolean(str)
      str == 'true'
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :likers, through: :likes, source: :liker

	#VALIDATIONS
	validates_presence_of :user_id, :title, :text_field, :post_type
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_many :likes, class_name: "Like", foreign_key: :liker_id

	has_many :friendships
	has_many :friends, through: :friendships
	has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
	has_many :inverse_friends, through: :inverse_friendships, source: :user

	has_many :friend_requests
	has_many :requested_friendships, class_name: "FriendRequest", foreign_key: :friend_id

	# has_many :friendships, foreign_key: :requester_id
	# has_many :friends_users, through: :friends, source:

	#VALIDATIONS
	validates_uniqueness_of :email
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
	validates_presence_of :email, :name

	#bcrypt stuff
	has_secure_password

	def self.search(search)
	  if search
	    where 'lower(name) LIKE ?', "%#{search.downcase}%"
	  else
	    all
	  end
	end

	# def banned?
	# 	if current_user.banned_timestamp > Time.now
	# 		true
	# 	else
	# 		current_user.update(banned_timestamp: nil)
	# 		false
	# 	end
	# end

	# def time_ban
	# 	if current_user.score == -5
	# 		current_user.update(banned_timestamps: = Time.now + 3*60*60)
	# 	else

	# 	end
	# end
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

 #  def banned?
	# 	self.banned_until > Time.now
	# end
	# helper_method :banned?

	# def ban_user?
	# 	# if self.score <= -5
	# 	#   self.update(banned_until: Time.now + 24*60*60)
	# 	# end
	# end
	# helper_method :ban_user?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    # @comment = Comment.new
  end

  def new
    # @comment = Comment.new
  end

  def create
    Comment.create!(content: params[:comment][:content], user_id: current_user.id, post_id: params[:post_id])
    redirect_to user_posts_path 
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController

  def create
    FriendRequest.create(user_params)
    redirect_to users_path
  end

  def destroy
    FriendRequest.find_by(user_id: params[:friendship][:user_id], friend_id: params[:friendship][:friend_id]).destroy
    redirect_to current_user
  end

  private

  def user_params
    params.require(:friend_request).permit(:user_id, :friend_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    FriendRequest.find_by(user_id: params[:friendship][:user_id], friend_id: params[:friendship][:friend_id]).destroy
    Friendship.create(user_id: params[:friendship][:user_id], friend_id: params[:friendship][:friend_id])
    redirect_to current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    render 'posts/index'
  end

  def new
  	render 'posts/index'
  end
  
  def create
    like = Like.create_or_update(post_id: params[:post_id], liker_id: params[:user_id], value: params[:value])
    
    @post_likes = like.post.likes

    up = @post_likes.where(value: 'true').count
    
    down = @post_likes.where(value: 'false').count

    total = up - down
    

    puts "="*50
    puts up
    puts "="*50

    puts "x"*50
    puts down
   	puts "x"*50
    
   	puts "o"*50
    puts total
    puts "o"*50

    render :json => total
  end

end


# class Game
	
# 	def initialize(board)
# 		@board = board
# 	end

# 	def create_cord
		
# 	end

# 	def get_row(row)
# 		@board[row]
# 	end

# 	def get_col(col)
# 		col_arr = []
# 		@board.each do |row|
# 			col_arr << row[col-1]
# 		end
# 		col_arr
# 	end

# end

# boggle_board = some_array

# coords =[ [], [], [], [], ]

# game = Game.new(boggle_board)

# game.get_coord(coords)
# game.get_row(2)

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if current_user
      friend_array_one = current_user.friends
      friend_array_two = current_user.inverse_friends
      friend_array = friend_array_one.pluck(:id) + friend_array_two.pluck(:id)
      friend_array << current_user.id
      posts = Post.where(user_id: friend_array)
      @posts = posts.order("created_at DESC")
    else
      redirect_to root_url
    end
  end

  def new

  end
  def update
    100.times do
      puts "======="
    end
    puts params
    # puts 100*"======="
    @post = Post.find(params[:id])
    puts @post
  end

  def create
    new_post = Post.create(title: params[:post][:title], text_field: params[:post][:text_field], user_id: current_user.id)
    redirect_to user_posts_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @users = User.search(params[:name])
    p @users
    redirect_to users_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if User.find_by_email(params[:user][:email])
      user = User.find_by_email(params[:user][:email])
      @user = user.authenticate(params[:user][:password])
      if @user
        session[:user_id] = @user.id
        redirect_to user_posts_path(@user.id)
      else
        redirect_to root_path
      end
    else
      @user = User.create!(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
      session[:user_id] = @user.id
      redirect_to user_posts_path(@user.id)
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:name]
      @users = User.search(params[:name])
    else
      @users = User.all
    end
    # @search_users = User.search(params[:search]).page(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    # @post = Post.new
    @posts = @user.posts.order("created_at DESC")
  end

  def new

  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:about)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user
  		redirect_to user_posts_path(current_user.id) 		
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/comments/_new.html.erb
<div class="new_comment">
    <%= form_for :comment, url: user_post_comments_path(current_user.id, post.id) do |f| %>
    <p>
      <%= f.text_area :content, size: "50x2", placeholder: "Comment" %>
    </p>
    <p>
      <% f.hidden_field :post_id, value: post.id %>
    </p>
    <p>
      <%= f.submit "Post Comment" %>
    </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Trainer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
</head>
<body>
<nav>
  <% if current_user %>
    <h4><%= link_to image_tag(current_user.photo_url, {height:40}) + current_user.name, url_for(user_path(current_user.id)) %></h4>
    <ul>
    <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
    <li><%= link_to "Search Users", users_path %></li>
    <li><%= link_to "Profile", user_path(current_user.id)%></li>
    <li><%= link_to "Home", user_posts_path(current_user.id) %></li>
    </ul>
  <% end %>
</nav>
<div class="cover">
<div class="centerwrap">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/posts/_new.html.erb
<div class="new_post"> 
   <%= form_for :post, url: user_posts_path(current_user) do |f| %>
    <p>
      <%= f.text_field :title, :placeholder => "Create a Post, Bitch....          (The Title Goes Here)" %>
    </p>
    <p>
      <%= f.text_area :text_field, size: "70x2", :placeholder => "Content" %>
    </p>
    <p>
      <%= f.submit "Post" %>
    </p>
    <% end %>
</div>

app/views/posts/index.html.erb
<section class="feed">
  <%= render partial: 'new'%>
  <ul>
  <% @posts.each do |post| %>
    <li>
      <h3><%= link_to image_tag(User.find_by(id: post.user_id).photo_url, {height:25}) +  User.find_by(id: post.user_id).name, url_for(user_path(post.user_id))  %></h3>
      <li>
        <h4><%= post.title %></h4>
        <p class="posts"><%= post.text_field%></p>
        <hr>
        <h6><%= post.created_at %></h6>
        <a href="/users/<%=current_user.id %>/posts/<%= post.id %>/likes" class="vote" data-vote="true" data-post-id="<%= post.id %>">
          UpVote
        </a>
        <a href="/users/<%= current_user.id %>/posts/<%= post.id %>/likes" class="vote" data-vote="false" data-post-id="<%= post.id %>">
          DownVote
        </a>
        <div class="score"><%= post.likes.count %></div>
      </li>
      <ul>
        <hr>
        <% if post.comments.first %>
          <% post.comments.each do |com|%>
          <li>
          <h5><%= link_to image_tag(User.find_by(id: com.user_id).photo_url, {height:20}) + User.find_by(id: com.user_id).name, url_for(user_path(com.user_id)) %></h5>
            <hr>
            <%= com.content %>
            <hr>
          <h6><%= com.created_at %></h6>
        </li>
        <hr>
          <% end %>
          <%= render partial: 'comments/new', locals: {post: post} %>
        <% end %>
      </ul>
      <hr>
    </li>
  <% end %>
  </ul>
</section>
<!-- javascript  text_field-->

app/views/posts/posts.html.erb
%section.feed 
  %ul 
    %h3=  
    %h6=
    %link_to 
    %li 

app/views/users/_edit_about_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :about %>

  <%= f.submit %>
<% end %>

app/views/users/_new.html.erb
    <%= form_for :user, html:{class: 'signupform'}, url: sessions_path do |f| %>
    <p>
      <%= f.text_field :name, :placeholder => "Name" %>
    </p>
    <p>
      <%= f.text_field :email, :placeholder => "Email" %>
    </p>
    <p>
      <%= f.password_field :password, :placeholder => "Password" %>
    </p>
    <p>
      <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
    </p>
    <p>
      <%= f.submit "Signup" %>
    </p>
    <% end %>

app/views/users/_new_post_form.html.erb
<%= form_for :post , url: user_posts_path(@user), html: {method: "post"} do |f| %>
  <%= f.text_area :text_field %>

  <%= f.submit %>
<% end %>

app/views/users/_view_all_friends.html.erb
<section class="friend_list">
<% if current_user %>

  <% @users.each do |user| %>
  <h1><%= link_to image_tag(user.photo_url, {height:45}) + user.name, url_for(user_path(user.id)) %></h1>
    <p><%=user.about%></p>
    <hr>
      <%= form_for FriendRequest.new do |f|%>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :friend_id, :value => user.id %>
        <%= f.submit "Add Friend" %>
      <% end %>
  <% end %>
<% end %>
</section>

app/views/users/index.html.erb
<div class="search_bar">
<%= form_tag users_path, method: "get" do -%>
  <%= text_field_tag 'name' %>

  <%= submit_tag "Search Friends" %>
<% end %>
</div>
<div="all_friends">

<%= render partial: '/users/view_all_friends'%>

</div>

app/views/users/show.html.erb
<section class="profile">
  <%= image_tag(@user.photo_url, {height:200}) %>
  <h2><%= @user.name %></h2>
  <p>Member Since: <%= @user.created_at %></p>
  <span><%= @user.email %></span>
  <a href="">facebook</a>
  <a href="">twitter</a>
  <a href="">instagram</a>

  <div id="status_bar">
    <ul>
      <h3><li class="status">Status: BANNED</li><h3>
      <h3><li class="karma">Karma: -4</li></h3>
      <% if @user.id == current_user.id %>
        <li class="about"><%= render partial: "edit_about_form", layout: false %></li>
      <% else %>
        <li><%= @user.about %></li>
      <% end %>
    </ul>
  </div>

  <div id="friend_requests">
    <% @user.requested_friendships.each do |request| %>
      <p><%= link_to "#{request.user.name}", request.user %> <%= "wants to add you as a friend" %></p>

      <%= form_for Friendship.new do |f|%>
          <%= f.hidden_field :user_id, :value => request.user_id %>
          <%= f.hidden_field :friend_id, :value => request.friend_id %>
          <%= f.submit "Accept" %>
      <% end %>

      <%= form_for request do |f|%>
          <%= f.hidden_field :user_id, :value => request.user_id %>
          <%= f.hidden_field :friend_id, :value => request.friend_id %>
          <%= f.submit "Deny" %>
      <% end %>

    <% end %>
  </div>

  <div id="new_post_form">
    <%= render partial: "/posts/new", layout: false %>
  </div>

  <ul>
    <% @posts.each do |post| %>
      <li>
        <h4><%= post.title %></h4>
        <span><%= post.created_at %></span>
        <p><%= post.text_field%></p>
      </li>
      <%= render partial: 'comments/new', locals: {post: post} %>
        <!-- <hr> -->
        <% if post.comments.first %>
          <% post.comments.each do |com|%>
          <h5><%= link_to image_tag(User.find_by(id: com.user_id).photo_url, {height:20}) + User.find_by(id: com.user_id).name, url_for(user_path(com.user_id)) %></h5>
            <%= com.content %>
          <h6><%= com.created_at %></h6>
        </li>
        <% end %>
      <% end %>
      <hr>
    <% end %>
  </ul>

</section>

app/views/welcome/index.html.erb
<section class="home">
  <hr>
  <h2>The Anti-Social Network</h2><hr>    
    <%= form_for :user, html:{class: "loginform"}, url: sessions_path do |f| %>
    <p>
      <%= f.text_field :email, :placeholder => "Email" %>
    </p>
    <p>
      <%= f.password_field :password, :placeholder => "Password" %>
    </p>
      <%= f.submit "Login" %>
    <% end %>
    <button id="signup">Sign Up</button>
<%= render partial: '/users/new'%>
</section>